services:
  app:
    container_name: backend_app
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db_users:/var/lib/postgresql/data

volumes:
  db_users:

