services:
  app:
    container_name: backend_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_users:/var/lib/postgresql/data

volumes:
  db_users:

